spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ecommerce
    username: root
    password: 1234

---

spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 1234